### ISSUE TITLE
error processing 2019/09/21 meal

### ISSUE THREAD

**Issue by stonylohr** [jkimdon/cohotikimeals#111] opened 2019-10-14 04:17 UTC
From Nic
![image](https://user-images.githubusercontent.com/6233925/66729216-d30f9280-edfe-11e9-885f-1507437ab343.png)

**Comment by jkimdon** [comment] 2019-10-28 04:14
Incorrect error message.

Duplicate of #110 
I believe the #110 fix will fix this meal summary as well.

**Closed by jkimdon** 2019-10-28 04:14 UTC
Labels: Priority-High, bug
